version: '3.8'

services:
    db:
        image: postgres:15
        container_name: yummy_db
        restart: always
        env_file:
          - .env.docker
        environment:
            POSTGRES_USER: ${DBUSER}
            POSTGRES_PASSWORD: ${DBPASSWORD}
            POSTGRES_DB: ${DBADRESS}
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
          interval: 10s
          timeout: 5s
          retries: 3

    bot:
        build:
            context: .
            dockerfile: Dockerfile.bot
        container_name: yummy_bot
        restart: always
        env_file:
            - .env.docker
        depends_on:
          db:
            condition: service_healthy

    admin:
        build:
            context: ./admin
            dockerfile: Dockerfile.admin
        container_name: yummy_admin
        restart: always
        env_file:
            - .env.docker
        ports:
            - "8000:8000"
        depends_on:
          db:
            condition: service_healthy
volumes:
    postgres_data: