# Generated by Django 5.2.4 on 2025-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('telegram', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(max_length=15, null=True)),
            ],
        ),
    ]
